forge "forge.puppetlabs.org"

mod "erwbgy/limits", "0.3.1"
mod "puppetlabs/concat", "1.0.0"
mod "puppetlabs/ntp", "2.0.1"
mod "puppetlabs/stdlib", "4.1.0"
mod "rtyler/jenkins", "0.2.4"
mod "saz/ssh", "1.2.0"
mod "saz/timezone", "1.2.0"
mod "stahnma/epel", "0.0.5"
mod "thias/sysctl", "0.3.0"
